import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div className="z-10">
      <Head>
        <title>Coffee Connnoissuer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="mt-44 ml-auto mr-auto sm:ml-20 max-w-xs md:max-w-lg">
          <h1 className="flex flex-col sm:flex-row mb-3 ">
            <span className="font-bold text-white text-6xl">Coffee</span>
            <span className="font-bold ml-1 text-violet-900 text-6xl">
              Connoissuer
            </span>
          </h1>
          <p className="text-white p-2">Discover your local coffee shops!</p>
          <button
            className="inline-flex justify-center py-4
            px-6 border border-transparent shadow-sm mt-2
            text-sm font-medium rounded-md text-white
          bg-indigo-600 hover:bg-indigo-700 focus:outline-none
          focus:ring-indigo-500"
            type="submit"
          >
            View stores nearby
          </button>
        </div>
        <div className="absolute top-0 -z-50 right-10">
          <Image src="/static/hero-image.png" height={600} width={1200} />
        </div>
      </main>

      <footer className=""></footer>
    </div>
  );
}
